---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgA1WEY06f3qhkkiCcLHOLTF+GCbfIsAdrS4I2c0vKG11/arEk+NUyCgyR/F9kUByJ0Fatm5cwLSRMIbKYCBZWUxc0p00D9J5neb0VdfFazrSXiE+2EPlqxDa+9dppFVe4jgUuw/oMrIj/NdmfiAbmwUysFc2rwDSIjsUU2voPpWR2hmPu922nd9Mnhgbv4dgl1R3Z+exmZS0LLKmtisuhc+G9hhE07Ui7QcAFCRj0somDpGXqGTix/N1QpCowHX/mSpqifrocNAfK9bdB0PM/KJpUnyAtwUMzHsbfbdkUNoeUcMpkekpCGHtqE0NNln4DWfCFiLmS8KT6SlbpqVFwvU0E6e0crlspvM1IbS11FnBKVbM7BLqgy8NgLSD0MmabQKa4rxsmc/GDGuxHa8zKE8s0G3dZWB/ZCupRnt1p4dfz9uqlCCude9enzN3qMr4rTT3ZKDCSRQ3+Y1W2/EmzL1YzCLNVYofFDfif9j6LVptvJ/+YGrmsSdif63v+8Tw8uoOAxWIts6Zi5+WcUMVxRqoCMYvySocgcoMYMQ0/ewWLWbexBOx0ZAuQX09m0/rBrrzB6LAJdYut2qK32ODowKurpYFBx6OM18nLezlQaAxMYgurOqCfp2EfSjmkKV3lV0FTGytwUe16+I9+GOKEgDtRLCx4WW7i/EtuLCo+jNU29a7kps2heLYBJvQI4u9/CavG9jL21kDx1lq5hneZAK42/TNnm+Mq2SOwBgC/Z05AO16ZzxtqBINq6iW1UcGC9qKKk+t+PzIUCQjLXiisKsK4Sa4hP6Y+9N6pGJMpVJsZRkCC7OI3rVZkckib7P+7WKHR4ubkUVuq/xnt0bFlP22CoWYu3NwN/Pa+BCpUUhPg7LCYfva/yhm/3zeDzqvMZx5ZmItPiouH/qsFImsRBNZLLMRLiAznL/ozUpvgvf
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
