fullnameOverride: external-secrets
resources:
  requests: { cpu: 50m, memory: 96Mi }
  limits: { memory: 256Mi }
webhook:
  resources:
    requests: { cpu: 10m, memory: 48Mi }
    limits: { memory: 128Mi }
certController:
  resources:
    requests: { cpu: 10m, memory: 48Mi }
    limits: { memory: 128Mi }
