apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - minio-creds-external.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - vieneu-deployment.yaml
  - vieneu-service.yaml
  - voxcpm-deployment.yaml
  - voxcpm-service.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/the-algovn/tts-service
    newName: ghcr.io/the-algovn/tts-service
    newTag: main
    digest: sha256:e62d7734ecafacddcfc1a6a76402b555b78a4f6fbdc8827242f9ff1e18df91e7
  - name: ghcr.io/the-algovn/tts-service-vieneu
    newName: ghcr.io/the-algovn/tts-service-vieneu
    newTag: main
    digest: sha256:922278ca911281365968f843b6104ae6d4391237d837df28ae1a61edf8d95d6f
  - name: ghcr.io/the-algovn/tts-service-voxcpm
    newName: ghcr.io/the-algovn/tts-service-voxcpm
    newTag: main
    digest: sha256:7871e0f6c35990a292380ffc7725b7ea0c7cad72fd54af350d9c8f9723a9886b
