apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - minio-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - voxcpm-deployment.yaml
  - voxcpm-service.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/the-algovn/tts-service
    newName: ghcr.io/the-algovn/tts-service
    newTag: main
    digest: sha256:85afe81049ecd14105a3349696e863ff4fee0ff8582c17de2bc277c101a549e0
  - name: ghcr.io/the-algovn/tts-service-voxcpm
    newName: ghcr.io/the-algovn/tts-service-voxcpm
    newTag: main
    digest: sha256:f7b7b6231616817b0f3a2a18a808f218d3c929f3a7488c1eac7987776bf940e1
