apiVersion: v1
kind: Service
metadata:
  name: tts-service
  namespace: tts-service
  labels: { app: tts-service }
spec:
  clusterIP: None
  selector: { app: tts-service }
  ports:
    - { port: 9490, targetPort: 9490, name: grpc }
