apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oauth-external.yaml
  - redis-auth-external.yaml
  - deployment.yaml
  - service.yaml
  - emails-configmap.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - ingress.yaml
  - networkpolicy.yaml
