apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-the-race
    newTag: main
    newName: ghcr.io/the-algovn/web-the-race
    digest: sha256:16c394b14aa74f74c74cb251af39ed2fdfa44d43499ec320e95a87e307eea5b2
