apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-the-race
    newTag: main
    newName: ghcr.io/the-algovn/web-the-race
    digest: sha256:d4772cf5cce01f928055e9ae1aa0d1d90b2e21d2058879ba528d6c16f8593ff7
