apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  ingressClassName: kong
  rules:
    - host: grafana.algovn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vm-grafana
                port: { number: 80 }
  tls:
    - hosts: [grafana.algovn.com]
