---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCQi2AI3U8U7dNyigDAKsgAybFEEO2Irm0qXKgDjv9HLLOxCHKfpHnJUCLOMMGEZwZh/Wx5Te5aNkv3JtqswDjui3rKgW7B4fzUrg5EAx8/pQ3oWp41eSr1F741gbK/6vFehJKyYYUJZISqMw0J5vGe/efxvDaC/ZOMsOP2XQxTj+IwRIPkXYagG7dgrb30b/mrvbwQp6+8ve3ufMXufVvraFIx2GNVftZ+R+U+NxOC17KNVLfexq0PYkxpEqxiZk6TaAbeM4k9ESwulKmg3WhvDI7AtQpRYKdWH9njyfz4Y17DDEBhnVIuDuBRVYOmGaKRJd1MQXNfo2eJRpDfNOxadbSCPZgxhA+/K42P9wwRdubHAGLEkyF3pl87RY/5yq1rmTCXMJzX6XJIPE9R+ApkQ+ZfRVrN6aSSlb4bigp4wi8FSb+h2Oo+/guv0osPrrn0qc7Z9F1A8pEqzFC+6+pfyDBlurqnXO8XWk4JjQl1e3zj5wOBv9a4SxUea7NZYExiCpjeziwC38iz54MMdf7HuSeR2jtVqQOqGuLb0/Ywgr0rU0NLyHnw/AJgmqwDpd2gudGDLUm0mQ7lnDUuPS67FvL5nj8kp7QFsN3Os1kuFWYH06i1Z0SZkPGTbsC9bDKFEELWvuORSLWfWOOHxel21707sRHQVAPxroR2lLIO+N//X1UfRhjWTI+pI38jlZeUUpJszaku6g4fl1U8t1UEOd7cH6LuSr6Aw+s3l34RwlsD52rDhYJGiPBEFBCzTtmpgLF3yZO4SfIFczlTdDvq
  template:
    metadata:
      name: grafana-oauth
      namespace: monitoring
