---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCTe3ahpcJ1U6SBGgUnRyl5Htjw9Xz6NcIcLevzDEE5j4cGjmqX/GtXWM+iPCczAE47u5UivVsmiydEocpDGqwshdx4UtLIWILPC/gMNaI2FDgnmGdjXfMKLIG0EfEX0GvgDyXFz9HV8+7XoMhBHeEuXboIYfz4ptN8yZR0lH1/gRt/zRnQFQdEoBuQXBYw6TA2gsWEBgOPNI7rM+NeZuLk81CE6n8daYIBXMFy+h5FgzJxD+IHYJDrKUVwnTncSipB15G87YMa/GIBBxaY0BDDNQQ9WT8jInmO8pEqGKgCm2z2JCZxlFjeJaW4CA/KDnZIBocHDAzCM4Sm0Vj2eEOX/11y8pjfkjrbVkFltm8vzRgTaN9TJjd7PN8dZxb0jjYde5Qdc1nwsvF3RM66elwt6LcCX/JhMJgvlSLa2jykSnUr5zeJ43+D2CtnMXM8uLXp4mWripK4dF7BuvEm2u2w6QahtB24Gs7YdVVsCCDEZfVIfgI6ql5t8cW5RyumZBeRlQhMa9gvd0w1PYatNLyxIVitP3+QFKMTOR5dXYJCpfMAclsbAYuRrDj31WI0n0PWy6k0zfTOrZ3s+Sx+iQoPNShgz09qixxMq8hyWKYuh8zYk7YmhlwKn0xIS9mHVEkJJaBoDXBgP/TOkTc+CfG4lDbablaqNpGPVY51qQY1tnmcU3/4HlqCIcEANT5hmngI+K5A3FVOvkBRNAb5pSnDLIvtU1DL6AJvghRReXtayg==
    admin-user: AgA7/FutlxfU5nsKySH2PclipVn+lKvz+cBu1x/fsHwS3AweD4Q2bD3tmugYYCsCYFknF2d3HhmzFufPb7Xh12rZ0qwfumakf8QwaUECdt5d/3qPwgsLV2ePe3pCOzPbUiiHhvbM75LBiPT//zUL/KKghezbA/9jDw3i4XzDOn4fiEhVSe0TElOJpQPissj7wMFGnPjjDzEE8TVlm8ByPQr/UfCSbFwuxcWHMEWT3nRy1J7osTUjD64sbkFb/Zyd5uo1uxm0WNHGJqj+zQNcHm8+ceSSbA2+x3N7kcNZdSJ97AHgwtoS7EEM9kv2vsxShaEMP8lDTgbjZq+E0wJbd/ah8AsM2d4nfgWxhXsRFZHTJa3RtTfiIZFzLxy3RU+atVLxQtZmO9GC9ugPygjEbyYW0Qj1dGLcTJv25YR5YbM+2WohH2z+DhcBVmTT3d5AdrWQ1meLNMwiuBi3KYaUD0yQQ8NVOH02DYSXbpIp0VtxLWqx/1/IPBW8IAtbFAaxy5TI7p0bxCgwX9SGQKdk76NYVph2WWm98p1G6QjVZnp1w722xA0ieFEZ4Fgh7izJc6XafS6t0dhD0mFp+cv3RckdbQDlehsULVMktBeh0G2+KOzuazCtRXGh31V/in6iI+fVjmfHdpdZ7fDpOjeKtp1BVJld7ss1mNfTnHhfMM2Lg5ZOrNDytCxG197FqHiTF+S2PZ7Xpg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
