apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-admin-external.yaml
  - grafana-oauth-external.yaml
  - grafana-ingress.yaml
  - scrapes.yaml
  - vmrules.yaml
  - blackbox-exporter.yaml
  - the-button-probe.yaml
  - the-button-rules.yaml
  - kong-dashboard-cm.yaml
  - postgres-dashboard-cm.yaml
  - authnz-dashboard-cm.yaml
