apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-admin-sealed.yaml
  - grafana-oauth-sealed.yaml
  - grafana-ingress.yaml
  - scrapes.yaml
  - vmrules.yaml
  - kong-dashboard-cm.yaml
  - postgres-dashboard-cm.yaml
  - authnz-dashboard-cm.yaml
