---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openfga-datastore
  namespace: openfga
spec:
  encryptedData:
    uri: AgCos2ofzSMnxvwC8hQCebk+LTTI7WllUK8H+b8PzK+OLRXtYHkl0fwKt6HJTI8giYZKieYP4q1kX90Bsn5OeXUE6GB0UK1fTBMeqc8q6BdVed/M0oqH577/1BznjC22zWXw3aZXsexxcWeoygKcDXCPqRIj0r+jWPVCQTmRQJthKZxMOPkmeAcvMZ2SVIds3Uhk8RhwVcN9EG6v7apXl7jXFDLaG+c4a4eIYiN2E6afITeD1YAF3Yzlv7LA+VbSxjWCZE3vsVKPlpjcdZXjiuy9ugIvCcTxYY3IRR3MOS8HPirK94AJx/+xZrI2XFyTLK8y4tVzWfRxn8xOlCfXImy+I6BJv2NzhLXW4pic0ZbvJRrHGE6TXQbJNV6L0pc7hrqhVNT9eBa+K+jDGyh/dV3M2zIzDtdnBfQ3WKi23VHxS9p+a+denC47GVGJr2OB6IcfxDhkcbizfQSHqufwEMEe2VKie+CKVK+QNnS2IIH74Xe94tSddIfYJNvTsw2jFIPvxVHI+U7goJBicN0tFvskat4Xm4vJU127kSHMm2oPN/IpeaDPtt+ySfH6CXGTiukUvxJeEnzhnKfTobAkrn1ug5PxX0koNBrBRcwqtklp0oFpufihMC90LIamCqYXiOyOu5qRIsffWTPo5SiBIbFS9YTTUHuStKyzCviL2szv6JE68Va9kcaXb4kpzviprgLuFPI1X0wmOu+ZNh6NtlwhQQkmbHhW3r1TKfkq7auWEfBViEqy/19n3WO3a/tB/6G+OYLIXHnfj8JahuHaLh9hcFrZG7s/pw2Pw3T2xxMulr2ITknXS5RJt9eGjEbnli0SliCzhA==
  template:
    metadata:
      name: openfga-datastore
      namespace: openfga
