apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - prometheus-plugin.yaml
  - podscrape.yaml
  - jwt-auth-plugin.yaml
  - zitadel-jwt-3815696693.yaml
  - zitadel-issuer-consumer.yaml
  - networkpolicy.yaml
