apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: zitadel
  namespace: monitoring
spec:
  namespaceSelector: { matchNames: [zitadel] }
  selector:
    matchLabels:
      app.kubernetes.io/name: zitadel
  endpoints:
    - port: http2-server
      path: /debug/metrics
