---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-config
  namespace: zitadel
spec:
  encryptedData:
    config-yaml: AgCQihtS3KkPRTv1NDpgVyMPjomb+Dxny6v6koOw+cbkcbHKUQLietdZZTzp+JGkuwVHNz7oyHpQ9HuFKvJeJnx0LAWCE/LYXmO4cM5nd9CzHC7OlqteC2yP4o5tfSdxxyDwif0p7gSkymrPCx3YYzxcdrfnJmyK+0/dK/1j6umjOFK29Gc4axIh+vlIW3WXLPWtt5so+D76I/6ikwUw8ZS59CuexC429enXi8JX5ZN5uXX8ZHPD3dRFF14hXfE1Gl3RmJfFC+jtPDRWcyGuVAhpycQUOC9toLfNR96RB3d8kBNTY5EYLvCDlrwW+rLZhk2OvRZ7k2rv3qWVIi843dFx499WN8+hrGZRpj2KA56pHTqQYrtoSP6F2DXKJuwXH1VvaTs3bagiXbg2cRwXYGsUz/aYzankSyedUlIFQe9GXqvgN/C0rilCFgI9IcTaB0cHAuevZaThBpj3eyjCWbgRBAhHyVjjjBV1SRUbEAHNRRAsRHhhu6gglJs7fxeJSfjvTc6NksfJGl2qFSuKVR9Y4vu/GyY/Sww9kZXAIqnym2WrTAmDTiCzbc1QgrpaaX5s5mMLEvJfOOklep3tDMPSTCUPsnCCIArL0m7/lzBZpANZm7HILA8i+/VgWwP/fZWXexHVL2CXetKew1RYyFtuct9MY8hkNMYr+aMUA04CokugT0Ppi6qhq5628STn7e70PoEC1xzzFTMrgl5hxp3RiHFQLwzxJSz3x6zbwq3UHKWcNaibB/Up/PNcph48iIZ5sQc0BZAtAFXQCH6gny4/6SpFRJsTtUh80TyPXxieGXxxT1oaPE/Bsxl5LiHh5ieRc+5I5OjE+lS9sHOjClTAseksqcIaC/lolBbEL0JS98oHtG4mVzKjd8nRGwhfDTOgaceh9Xttv4FdvhF8m2WqZCtZ/W2M9kU8kK3U7aUca9mirAwPcNHs4ITjeBTQB8waE8nOMTIysuw8rBsG6LaLK5NvnDzfdA0Xw5SUPepHxjqnZRWPNKVHVQ2LT83o3gXn1Rf5he8/NhZWioh7eQRy71kXL70iMn8vDKWN52nnDwitKY2qrcPPeiv71K4J2nn5GCOZQKzim/Jx41SqB+uY3jJHCo6EytGDJrvgvC01nhdv6xFWvX1cS02Pu6NxAjKiOGBwvxsf9QzTrvrm0eIgaWcJiRFQ48REjoBWNUGCdUJ+iJM=
  template:
    metadata:
      name: zitadel-config
      namespace: zitadel
