---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-config
  namespace: zitadel
spec:
  encryptedData:
    config-yaml: AgB7l7Tifsizm34bswzY/LDh9wyj8ZdzJOGbyEjKuwNLbyG8w55XxzrYLyuUlPZb5yx5bbCflKMGCiSku//cc9NOUPFW4xqMvF0BQU3ih00na4gDGQXB3J4v1isp481vIGOt3O7zsMt2Pd3+gOhwI5blcdpxVII+MUyCKCCEzen6wYFIXt66YJ9hGBdWQBC+DN2t9JSvFwyVwL3EcrYDKnzDPDUKaZkyXsE8nTb/FF1eS8pKQHObdSCRF3Shg3TBMGdrbs6UioltK/bTc5FVGY8YcIXZMTfScLkKA2w2jZm5rd/SusWX52YSTw3NubGisYe88ShLhYDWX+BjjRdmuSNltOGOZ5fcVBcRQlnpl6erbtgUbs4BTTCKKHU4U70oQZ9KZ4ydVasBdMHNuamK4ASPw8L90cD85NWhw+YDv6ksC4tZXXbHnT5TWSbQVZWToFETsMZzGNRHBhU6SoJf4CUyBNnBjTFRaBHh6iP4THeWS0WVLRploGgsQONt328BD9avhnv+YMidzLwJYpQgLGV2GmVP1CHR32CJYJza8TGqy10YSqy/sjD6l+wvucz7+w9upIq0RNtnk7QuNxBZmEOs/avyZ1VySqBxNCymEtNr8EI66XyIyBDoKJk1aNexjNJuO7tYihl7cpJBmkqhlU555Xu7xn+x5xoui2Ivj+tUWg4hmw1q0bIoYOpuCLfJmsh7OkS/DhaxbHp1HvkMQS61fx8xOyd3H6LHJbIV1TlgkqzGLTRv95EfV15Nm2WuORh62DAwzgLEYEGvZP4/7a1GxBBW/1lGVKP0SNmMRkrWMgzqNHcVBwpupsoznZfXdOm216eBDckwXYIu/A3SHKEMYE9JMjeEv2IM4Go51XIiNcJN0fUem7e4D32kwqms1mEYnkOB8YpFnaETsLaJJWDssEiGswUwvNQpniGvF8N0kqbu6cxpbbBIMUiQJrrIWjz7Itu2Tvs2zGHNHp+FxlpvYYzfUb7K1X4ibYnHKaWj42CSgufUdTHgsDTmF3n/0JE4Rhpn3lFfulUs7E6WtvrmeqoV7VWefLroyElpJ/sJQAIT08DYprhC6NRLCRERuWkG1T+5j9t0nqud99WLEIEUlEfYSNyXgX4V//tTeI7DbaXl3Gcetn2v8je1Ka/M6qzmFMSoCmHfVj5smKMSXmyM1t1vOgJc7bvccwVNxq/ye9nao2U=
  template:
    metadata:
      name: zitadel-config
      namespace: zitadel
