---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-default-user
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgCO1PInc7FigOS+a9Sm6qg8+O0/nXaODBIkeFCuK1h6BqusQoDn5WoRFA/Ww/1g9rF5+vjhl7+WhhrcldDpwUeVUThlgGVtKRTx7bZV0Exp4piyC4Amt1B/1quNwL/8TlSZPBXPFgfS6Qez7GwYQE/oIIKc4kWJWEQvG85EwOlsrHLiQjhLl0IbqFjjSMriHdaA//4cRJ17v3buY5g4lU7Crn8n36T4hlF1mXCF22JwZ9xhL2iRl/yGQl0DewYb1LNG+0tvS5VJIOKQtTTYsbFgyZ1SCk6CduYbuKnaJ4op/tofRrTDRVMlmKnvu7Xj+ZxflNb2CLNewHhwcZ1cltCtRfnxpOUc/chtUSISJ7IGTE8QCUuTTUmukAssgqgk1q0FclSIIPuzKZSr2TQh0vovHKp6OS1mQ2RunGcX8qdpf9f8ivqaDqIfrlm4M+1EgNWnsaPIPXmQVdnMUXDZMKHfT5HoxCdvzn8HZqT1Z+423Wtnzg6sJBN4ZCdv3M4GGWc7yvy3MBKHw+gEQFW7IRd505CFMxR2+eNZ0DI0ZIhMjb1jDDhM79h1Sfxk+JlcTj1Kj+508gcHw1/Vyk/dABhZJJJr9U14KL15NCJ6d7XOfLYmdQDjUT3/dVKFbwpqXQTcfpgmWSU3OQhr7mNbsjGtl8tKJO+yXjgqL40PxXylYtDwhhHz3XAABZ47YkEefRjqFdiB4kC73OuabqQG4k8lXyla5HNi7ip2gOKJdU8EAA==
    username: AgAQ3jceqhUB9iwG3qNRnNLDj7dL4UuJgr89/XyQrwsMEwkkNWruSZ2m/rAMWe4QhdKQtRgcOH2FJqYJfqOK3JDcjEpS6r1gGuFHtNO6Ev+KKx74HUTUMbr7r5MALa2fD2PsZKHIwGy1lsPK21EyQg4ZLsnEfZ8n53VSXlymtGdhW9u7qKEqmv/wbqg2XxdxU7Vcg0wulrKMBqnDhsWccRVWNLqhXZk67CVZ3atMPTFgbjYPrDb3D880W9htMBU+xWmp0nE2V01cT29t3Blx8iq5UwBv3dpNKDhLMOBHwBVq/5dpL39c2Jdx+SXiF0NdjZnYxQtsZFVg8FU9oPOTheoaX7yoKgsVLme2QPC+697nsBGJ7UjiLW+By0ogUexTF2gdQN5P97geqcBF/UEUU21VJfBqVbhywFPKpcwhOM2LecCdRRzqHcvRi5xL/00n4tdq8nb6wUOZhR+KF6vwE6OvlAsvBhaneG05nqmEYeaUL94LZgiSpzPRN2RdDpRr8+VBejaRic3Ig9OZKY9Fwmpisr0DzV+odN5KJd9HQjttguqxbypUaCddT1/m/Ef33vcdphlh+r4S2cC4dApNA5oqdRa1v1bbuw3nRG40qo0j/4mVrwGrqA3uvypC5hd/JSQMP9dPM1YH7sTrs+szIVgw17ETwmdoQ9GzXID29tFPRhVxfTYszqoAcDm6Z+08A6Q7urAxCzk=
  template:
    metadata:
      name: rabbitmq-default-user
      namespace: rabbitmq
