apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: algovn/shared/cloudflare-dns
        property: token
