apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/the-algovn/iac.git
    targetRevision: main
    path: apps/landing
  destination:
    server: https://kubernetes.default.svc
    namespace: landing
  syncPolicy:
    automated: { prune: true, selfHeal: true }
