---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAAQ/hrBifo1w5plVs5O/i9qbkwYsl/XcKuuaTGnnX1ck3RLXRi+Bc+Epe+qZwHdLNThdg0J0n1/Cv7qW9b73aaM9SnKsyGpGqYW8qY3ZeFE0epOsFEWq25COCCY02vCx39hV7lkkAkIS3eXgtkfkXzbTiJq1WMntsED35ulo5pBClZ3ZR/PKECvRX9Z7WkQDsI/iha+YhQDYhilyn7ivGTDH03ueUtdNxVBDwcsRnf5zORtH9U4cS/S/WoGobIUnPJ9ya99hfszou2Ng0U5WRblbx6XLePg3jAZc1mJvbJGBGWcOAckZfUXX/fVEm/9VDr889qAmwhazjZzy8LqzaBe60PE0yWKPafuNRxibdqCAR4Nj7YUCkeWMiP3jctPcH9gvtqQ8w7fCoiCE1gEBLMqO20UUOT2uxzjcmxmvakyza4TLzt1lDF/s9pEV5Ub447tak9IihQ9AyCkSIh/ZfHd0y46ElUC4ikVHLqVp60bslqNBEFxY10wNj2VhgbqphQsvNmSUTEZiG92avDN4Yjifju+BnN4I1FTY0vpl2MEkncUPC81McNgEnCP4TNiDrQjqRXHb/CedNRwioj5s66rlC5xBd2SIEtPEjglhfBaP5oNOfkWOJbdFn83QGerdJrUs9/KileJXUEDVuFxzaYAGohlZ6bh8Z6T8EH6fe+q3IQTXeuzzXYNc8tXAkNu1bFy7R6x4A/x/22o48bAiQt2DNCjaP/gtpnh52191qUCSpOrzqK2sbbI8zZlOYptuno+/nE4A==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
