apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - pg-radio-lab-external.yaml
  - minio-creds-external.yaml
  - llm-keys-external.yaml
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - topics-job.yaml
  - networkpolicy.yaml
  - ingress-live.yaml
images:
  - name: ghcr.io/the-algovn/radio-service
    newName: ghcr.io/the-algovn/radio-service
    newTag: main
    digest: sha256:a1040db33e8e8fc0d2a67c0f3164beec3aaec46079a8faed5f45980426e93cf3
