apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - pg-radio-lab-external.yaml
  - minio-creds-external.yaml
  - llm-keys-external.yaml
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - topics-job.yaml
  - networkpolicy.yaml
  - ingress-live.yaml
images:
  - name: ghcr.io/the-algovn/radio-service
    newName: ghcr.io/the-algovn/radio-service
    newTag: main
    digest: sha256:a7ba1f1bd985a76b33dcb4129b9cde54d93a8fc4fd919636dca0df5855bedb16
