apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - pg-radio-lab-external.yaml
  - minio-creds-external.yaml
  - llm-keys-external.yaml
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - topics-job.yaml
  - networkpolicy.yaml
  - ingress-live.yaml
images:
  - name: ghcr.io/the-algovn/radio-service
    newName: ghcr.io/the-algovn/radio-service
    newTag: main
    digest: sha256:1c7e57ddd09c5901cb9b89f0d1cc871939bd2b3193f5f8f193c9a196d5688f5c
