apiVersion: v1
kind: Service
metadata:
  name: radio-service
  namespace: radio-service
  labels: { app: radio-service }
spec:
  clusterIP: None
  selector: { app: radio-service }
  ports:
    - { port: 9290, targetPort: 9290, name: grpc }
