apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    metrics:
      prometheus:
        entryPoint: metrics
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    resources:
      requests: { cpu: 50m, memory: 64Mi }
      limits: { memory: 160Mi }
