apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - pg-the-race-external.yaml
  - minio-creds-external.yaml
  - the-race-anthropic-external.yaml
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/the-algovn/the-race-service
    newTag: main
    newName: ghcr.io/the-algovn/the-race-service
    digest: sha256:17a964ac9887f99ea45be621d2cd3636442ceaad31ca9b19d1466af6ef9b0060
