apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-the-race
  namespace: the-race-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: pg-the-race
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: algovn/the-race/pg
        property: uri
