apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: amqp-creds
  namespace: the-button
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: amqp-creds
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: algovn/shared/amqp-events
        property: url
