apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - amqp-creds-external.yaml
  - redis-creds-external.yaml
  - pow-secret-external.yaml
  - pg-the-button-external.yaml
  - deployment.yaml
  - deployment-publisher.yaml
  - migrate-job.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - service.yaml
  - service-publisher.yaml
  - vmservicescrape.yaml
  - vmservicescrape-publisher.yaml
images:
  - name: ghcr.io/the-algovn/the-button-service
    newName: ghcr.io/the-algovn/the-button-service
    newTag: main
    digest: sha256:820611c0b12640879bc893337decffa2bcb4ec64b048211b049f4c62869223eb
