apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - amqp-creds-external.yaml
  - redis-creds-external.yaml
  - pow-secret-external.yaml
  - pg-the-button-external.yaml
  - deployment.yaml
  - deployment-publisher.yaml
  - migrate-job.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - service.yaml
  - service-publisher.yaml
  - vmservicescrape.yaml
  - vmservicescrape-publisher.yaml
images:
  - name: ghcr.io/the-algovn/the-button-service
    newName: ghcr.io/the-algovn/the-button-service
    newTag: main
    digest: sha256:2a17c510e2160f284a301767cf29a473a16bacbc387fc2b6ba4f5c132572be4c
