apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - redis-creds-external.yaml
  - pow-secret-external.yaml
  - pg-the-button-external.yaml
  - deployment.yaml
  - deployment-worker.yaml
  - migrate-job.yaml
  - topics-job.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - service.yaml
  - service-worker.yaml
  - vmservicescrape.yaml
  - vmservicescrape-worker.yaml
images:
  - name: ghcr.io/the-algovn/the-button-service
    newName: ghcr.io/the-algovn/the-button-service
    newTag: main
    digest: sha256:9e3275a60fd9344cf0110996bf6eac9fa736df6915aeb6cb55a93f843892d96b
