---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-the-button
  namespace: the-button
spec:
  encryptedData:
    uri: AgArIFlf7QKyMkVYx6NUMSKblYjFXEM6+2KSaLI9eaLBTxzLa2zB3goCoaqRXXZOaAbRMa6XFfPrw5I29z9rcOwVtNItDX54+ZAIDlzB211oVBvftJuZ7Hn2uXxH8RXgEImhRX2OMCV1Wzc6uJta/2JN+AIL1SQX6JOw2tBKFNq4BFzEjHq6fTuFI0fFiz16pfUUTlYSUoS5vCiQgbwgjwZnxB051VdhnORkpVj4xZaAAazSlFZYqcgyM3ZQjXb+8ztUtpTdZkQxgr557d9D8c3lJoASfOc1pfL6IBn/ZfwQniVAnDA6KQPQFWZ9+L1NQqMdPRZI5gCh+luQfdUY/LedgU0HBf1XSUoF1hhcx6zU3AJ0X4elCJASx7Xz2OaHXTcfvzmnhyvar6fKx/1VeioLZvalh/pSrNSBPpXv8dVhrxtI9uX3XYPIR02ZlNNXLDPJ7J7ws6arPP4UbZRZ3CkMqjwAmL6qnkM3gXWUgNV7dApjimycxhV5NhcyUfkZOqMqjn0jAPWTqBc/nRAdNdSaZ1eU/GOXRS9J62erhZSFyv+Z6UGsJewhkC1N9EuxctxLmx3czIoyeHkhFBFpdk6bOyGqQIVEmES8Jet9IIMEnIsQ21jQcyO1vohMfa9kfu9OlQO42TgvXgxKLZY/58VcbldRn2WRGnHMBB8no0fKbGenDNQl1llDgsEGSMwhCJhQPp1te+Rh7OZXdQ0nKWlQzWRq9EdCTiFfJ7mUSqGzsVgl7cuLmmnuCnjpbDhpq/icRzWDDuOrnK5anlS1HBd8WaM+J8leIyvbropgC0fgnI/NJkmtFdkvCSAzQI4M1Wy0gAonCZXvDkk1aw==
  template:
    metadata:
      name: pg-the-button
      namespace: the-button
