apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-the-button
  namespace: the-button
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: pg-the-button
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: algovn/the-button/pg-the-button
        property: uri
