apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pow-secret
  namespace: the-button
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: pow-secret
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: algovn/the-button/pow-secret
        property: key
