---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pow-secret
  namespace: the-button
spec:
  encryptedData:
    key: AgCk60D4gs2sF8yxEJv/DHnpwMYc5yCNXzgmN8SKfIPS74ijCpJLw+nfEgLwIaKXvnZIhongg6eOROIuUN3rycfR7mR9uK+gAP5N4D2KRHJrFPFDRFcizsDpHzLrS0vUatdxK1ikMBvnKtZgQjM80Bjex2+ICQhvueJASvNtya78BKAiultVSgnxlvQHl4xrYWqEWVJ2tecJBdAV1nmUNGzQOVDhq74CnNq1E/FIoy9K70lMh0V1/6B2E+tIHsw1UE6ESi4dgdOwdkAuJ6V7x4tV/2sz1xl1rNSfZuR1TKq9BN9LJur3LMgU+2feILLMneRNifeuyCwn581TVdI4LNl8CbLJXmt+vlzCfeGaRUpMEXGdDVUZsgnEX5wLKEhAcVkE+DBSo1tgLpRsB48Bq4t1Fw38KM/gRSXQT8wZ2XmkfMfe6KGtRDGwAC9qXhwhJp/FC2q+4kq0kvIr6Y7o7FhRYeXPbAjqxSoTecTrmO5RfwpZ+TPyMyR60qdo3W25f7MKuQps4yuzNZOw6i2d7VhPd9X9+FyUV8l1NeR9Do9nFyDndGVa3Gl/Zgdw3DtGzRIYVkmt/i0pbW8yovMId7AD1DqCYKKdXFK1IdIqO+zmgc8SgieIxp9I9B8/wTo1aO/w0TisPLAG7ghgICLtwyhkA15Ka4s1xjWhJTnKz9r/b7lxniDn8KGMwLGApyazzA2wBMmPA7o4lnPkkafOlcgISKCDtc4biAZNx83K1LeWDfB9IGatbkx2jsrquw==
  template:
    metadata:
      name: pow-secret
      namespace: the-button
