---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-creds
  namespace: the-button
spec:
  encryptedData:
    url: AgAi98Zvh1Z4xMps4I/5s47RfFS58CcLfCN53OByOxFowGXzO08zTmF9CjX1xIwXXq38VdMu+fc4nOk833GftqlfwxQH+DbjXS+ynjmZxQxLcwCpJpLiewrVB/mMyScwSrup9miqojQWR3OstvxI3j2yXNPB0evVFohm0N7vhRm61l7cOGeot9ohpr5Nu987uK41co/mpVJHbcoscvvf4FgDuU71p6HyxL2yoRy7BV6JSrd6ggSOQVvB68Rns9W217/3dhI++iY+0J4q8DyOKV8b7nDNbkLZh6QmGnCyO7nsPPrr/K4/9bt5KwGV6DwvWdg797c11nJEz/EVjYl74IwNT64gkLL3uYMxnJn+aiBz14bjqpg8tl5WVnTzyGVQjN1inK0B8jymZZachszUi/7H3NtVBYfNc0YqRER8aQyYDi7OV1Jq1pVpMsZLPe2QP+k5z+VqcFECQj5ZSZWs84bbI+gfaL4Er9kxHDmiiGdim1AyDXBPYUnQkCKKij/btqtVt5ZULD3ASLzb1KHW6V96txwG9Fm+xtK+CJYzx2NxgjqZT4lDdbkThzpXE9YNjTjZ7Petd2jCOJYzqRjc0N42W7dNuAO4uxPzMhqKHHVGYNZTYOQkCZVR4Zs7H/uLUZgNpnuTZFcJ1sOBCaGlW5Mhs/nDC83XQ0Hhm8B6/TxDOCDfyjH+PrnoZb4G8R5qP2wGkaANotCT35Ho9a/d+6et8AC0DYthJPDYpxO7xo77gxcl0xFwWwhOtmxGr6T1ZIrlj4cjrCBa98LFqdg0v/UO/KCrKCyAAciHvbvIsAn2/4BI
  template:
    metadata:
      name: redis-creds
      namespace: the-button
