---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-creds
  namespace: the-button
spec:
  encryptedData:
    url: AgARLu/nMHcwto01gbjyKB+AXEF52hpaY1E+yGXViv8iFR8eP9Y9wt5WqlUt9WqlQjNZqImcKKbqg9HVvmajyRBg4gd8KlBUEj906SKV1vZZjxbMbxEkCT47tHNNyvUeZtN1xdTnD4HSdMPQZbW8gJlo4wMEVCeE+Sg7C1plvQAOc/mByyEmPF0O8OcNk1dMygNP7dZXZMjbIYTyekynVweSlESDkDhdjtSwmj0CxpIYLol3nypflMiVAL5GCA5251AQ0s0od/BLQtboWotQjByIrkqODK8PpzZXQN/7pmnbRzm2yig5Grh0TnGLTSWJbSHmKVnKhKvpphyd9nh5nKoSZKDoQ+6hLtNuhUpZ3rVgfux3SsUrj+WP7CMU+PpLdPdy7D+sgzOoXXWBxE6iMSel6SKONb9Xu+et99mxeEKHW//zlNwRKz6qZsfdii1plfWIAZIQ9mT4uR2yMi1IRmDFn2pSCcPfYz46P55Qk/5IAL2EDKRrMCrpq/HZd36u41wtXyRQrUhRvoR6G7mtU/L3LKQCA0n6dFa3Do57GEiFEMzRA40+cnhi+JAPYKo28Xsq1QFmM/QncOjVwIeZ0fH6NxCmrmWAAWJXAnF3X3OxMkRK9XatV4hj+BNTGO5HXuQo9TolZ3qcx6ttGoJT1VGS0EWqT0xDIJdvij5UlWN2H1Yl6x0ioY4c9Hcrmo+bFlqWSBFudzohov6gpL/8EtChfLywUML4BMfTbGcYJX4RaWOQgZUI0ZVagP76XACgC150DmuqwXXo1Apjw/4XXYcdO1drjxqDen6jFraZ3i0=
  template:
    metadata:
      name: redis-creds
      namespace: the-button
