---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-creds
  namespace: the-button
spec:
  encryptedData:
    .dockerconfigjson: AgB2iQ0krh+D/KoLzPQmCfHt21V8i/ZKCDAA861bNw/B3LY1yzjO1RqZca67r86PZLxmrRmdk8jMMW78LbMn6EnZUOkEcKMijwVB7nbUvgmQQ+FGvGlnDhzMNgBGo8n5gvdHaUCG9Jjmf01+OESW2ytIWIJPRZ6dP7KxqNjlQ0sQnzqiWQrCylkvF7Yc3zRbzw8lTiKH+zRd/j7s433BCSikkL+2lK/Afig9nDjTya+bDZSoNcyra8jVBCP5YDnysSsjcVPHyTBLca6oUgz5xjgvZlSOkMrHc13TXVM6C7kow8pu8cRUsDepxpgTLaIut4gnGvmya8qb+oR+bjoURAXxWDR8L5Pv8nUbr2RugI0Xsgx/hBY4piJwOi2vrTcunEYp+UfvfzPod3smnILHlM732b8mp7c4TeGuPQL2DhcVtDEpxzlh1fbLUhfzPXvpgSd/7vu5lH3389u/W4WoyqmhYYQDxoqmh7tt2mTlONunOmf+DM1225OK/jDv31DvZHz2wDvX4OEeHbTszlIreORrKe/tUPhjmpoa7VwXIvgk5K7YkL64yeH1LqgAQWtOld5RB81TDWz2unZuPWW/EG3rr4MIuUGYIE7GAiUEDFtT0De9e9ZNEijUBoDvAKLDn0iS65qycVBPLy2A19/ZIY3TAeQX+EKQ2/2QAHV1y98y4t/+e6CRhCkhjvc5kBcfwmDW4T/CLnq02kWS82Ac7rUyn3Vbb53hzmc0zqX0piTp/Zkg+/Q52LdepoXZaFyc9vnr5ChfJhrm8FDgFW19jiqwaa8tR2Pwxx0iorbcn/K9TsvR21KlAR771d0vw6ndhqcL1hd7I34t4qP4E8HTzpjzGQdr6pm7rf23hHRx4AVO7S70PW3qjnXFk+I82sJIkdlC3B6DeW20ovdbfVyrrudLU8dO9LOfLFeIcDNGjMjBkeYW
  template:
    metadata:
      name: registry-creds
      namespace: the-button
    type: kubernetes.io/dockerconfigjson
