apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: the-button-worker
  namespace: monitoring
spec:
  namespaceSelector: { matchNames: [the-button] }
  selector:
    matchLabels: { app: the-button-worker }
  endpoints:
    - port: metrics
