apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/the-algovn/iac.git
    targetRevision: main
    path: platform/minio/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated: { prune: true, selfHeal: true }
