apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfga
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://openfga.github.io/helm-charts
      chart: openfga
      targetRevision: 0.3.10
      helm:
        releaseName: openfga
        valueFiles:
          - $values/platform/openfga/values.yaml
    - repoURL: https://github.com/the-algovn/iac.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/the-algovn/iac.git
      targetRevision: main
      path: platform/openfga/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: openfga
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
    retry:
      limit: 5
      backoff: { duration: 30s, factor: 2, maxDuration: 5m }
