apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo
        valueFiles:
          - $values/platform/tracing/tempo-values.yaml
    - repoURL: https://github.com/the-algovn/iac.git
      targetRevision: main
      path: platform/tracing/manifests
    - repoURL: https://github.com/the-algovn/iac.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
