---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: amqp-creds
  namespace: demo-service
spec:
  encryptedData:
    url: AgCIbMpnxRyMPHFomxTHCFmmi4aLM4vb936ExRfMm/dsGsc+Dgl5QjKD6IGICk3BkwgxNxJc+MqWSlkkKA5qCOvVIsqFXBWsbyzMAWHEmvrp+vOI609hAVGfQ0rXQFYCziaGtoe1kWTjYBD5LvCmE6N2rmywMPECjXO0BpADsdAYgwUzfVHWEnXO88OX/dGeADHDgD7peZ5waCHiIUI7ECeUMwi5FJ8U0X6MyNVkEqIWgguqda4kF3WLeEYJYbMXRsapgV0aMuoZAweNHZPe4bdYBWJ1J4eu29IsQQlxcOfoN23N51XoCSYbSOZOsfgZ/EE66Qzvye6MdzjYbz3Te+ef3u7ZFO2gDMvMM2imlVU0/yIws9SSwa7q+pWPwP0qPXpgCEWbnLq3y3YLL1MF6FtA8O8leLU89SDu8rH3+po82mwYsCj18mAs0e1BypKl+TqP74qoQz8wOce72GCeeflO4nhCoaQVmxPQwlY+gdltnZa3Uf9M4HxuSIaW/zo2EHBPgGU2unDvsxGOOmKVW5BSeFlqcLhGHChIQ6KeSXMxZ4sSW5xcjFpT80K0UreP8MNrt/WC5kfdQm/5RYw4klxl0KfdgE3p85t/LHvjPOt480UZXd5v69Wx6/DBFEg5XuVKsgRfK3lKBN+MWxYw8qSw5Ft5Uw3Qe8clNTqpJWWUdO3NJ9MlxYvvrtu7xKyke15ihQ8j1VwiMSgVb5CMC7oy7c70J7WBtzCMWECU5rCngN72T/ee1WqPyXd2nzytkA24F1GX3rIDDLWfw+XaW66WrvSlDoA/oo0ab6KajP9laj9VtVGCoc7O
  template:
    metadata:
      name: amqp-creds
      namespace: demo-service
