apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - amqp-creds-external.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - vmservicescrape.yaml
images:
  - name: ghcr.io/the-algovn/api-control-plane
    newTag: main
    newName: ghcr.io/the-algovn/api-control-plane
    digest: sha256:ee1c7a6947cae4207458320692e137c1b828c702fce75361ef807f54f450a378
