apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - amqp-creds-sealed.yaml
  - registry-creds-sealed.yaml
  - deployment.yaml
  - service.yaml
  - vmservicescrape.yaml
images:
  - name: ghcr.io/the-algovn/api-control-plane
    newTag: main
    newName: ghcr.io/the-algovn/api-control-plane
    digest: sha256:23e7591e31097ac5e8c7fffa4da9cb06dd6e58d19d245cb4f97efa07103ed5c6
