apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - amqp-creds-external.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - vmservicescrape.yaml
images:
  - name: ghcr.io/the-algovn/api-control-plane
    newTag: main
    newName: ghcr.io/the-algovn/api-control-plane
    digest: sha256:967be677459bc6af90787fc4c4c66dcbbd70bc0122b4d2c5ea60be4d8658dfeb
