---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-creds
  namespace: demo-service
spec:
  encryptedData:
    .dockerconfigjson: AgACmAUn1vQ8TUyYh9G/0aenvrGuanEypOCPIeS/sVB4rSguepXNNWdecgk2SQUvvhLy8lplK5E9q9Gb8aDxOjnKPlQ3wBpMz2QpJLQs0T5jUOZlisMJTJktyws5ScMCvYW/qXD1BNn1rpTnf7WN+gCWqOffLK2eu/7NYYMkW0iDn1UMoraphUdUnG5YozDNsaEX9Mo/3pqU+qEPRiJeYD3ruqAeUuBT/9tpgNTArLODAGWV3QXfxEfLisV244ZXvSItyut7JgZZpfrYibZUYRUr+i8GD2pRSgG890z3u26fltZQ+Tm5uEoOHTjvQe4hQFdeGYou9lXaA63tUiyo7cJBp0hOAhACUhYPly2u9AmyTJDDUk9t+YTI89KsY3WTa4ZbBNxrfgq4NpsJLp462G8zCavACBTLajxGlmN02GH6vS3ExqoKzgkdGY3mGB/5oiLXxAjZFGxusdoW/UtJgs7WQzE650YLsVJePk2fn683dQ1zghKdzzLig/0T02iC7V+H7veRvOW/9Opqj2/9I0gQ+coI/5ipbQqTMmsaeUb4g/Mc/TRZFbNubIAZ2v+iE3YKEZB3l3QENBn8SwDIdRqjD35I8dkRESbx7J9Yt6IQhtZsGoVIbXEnNpqKEZSNtBObKSp3QMmvp4G/regi7hNuoLFVHooctmJ2BrLbq5nO73QxBjjsDKtiV9aFwFvGez6nM+1dsFPz6/9+6jcvCyl8lCTRX6l5MizFCalFnmuqaBjJKI1asBngQKUUBx1sltwawVhkDOdMcygcmbSUuOeo1ehlvlKi8eXmxe5z3FHpOua3m7NdEo2ZfyDtvAZoMDl9+AZz6WWNEz70xUqrPIlLsGnZ/XtFfP0j4IhJ58F/9e+fesP5AGo+E5zL1//kC6Op9y52R4vjGNfMOXFkGfhZeOEMOilpa1xyjXFzfOZecqZ+
  template:
    metadata:
      name: registry-creds
      namespace: demo-service
    type: kubernetes.io/dockerconfigjson
