apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  serviceName: uptime-kuma
  replicas: 1
  selector:
    matchLabels: { app: uptime-kuma }
  template:
    metadata:
      labels: { app: uptime-kuma }
    spec:
      containers:
        - name: uptime-kuma
          image: docker.io/louislam/uptime-kuma:2.4.0
          ports: [{ containerPort: 3001 }]
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { memory: 384Mi }
          volumeMounts:
            - { name: data, mountPath: /app/data }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources: { requests: { storage: 2Gi } }
