apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-minio-creds
  namespace: tracing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: tempo-minio-creds
    creationPolicy: Owner
  data:
    - secretKey: access
      remoteRef:
        key: algovn/radio-lab/minio
        property: username
    - secretKey: secret
      remoteRef:
        key: algovn/radio-lab/minio
        property: password
