apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-the-button
    newName: ghcr.io/the-algovn/web-the-button
    newTag: main
    digest: sha256:1bd3e27eedc9cdab10adc64a8a054f603159a7df17125e9d030ee8388c92a403
