apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-the-button
    newName: ghcr.io/the-algovn/web-the-button
    newTag: main
    digest: sha256:3a90bdedfc34b11f0eda2fdcdfe3f80e85d36f458dcbdb11adbdb1949006819a
