apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-the-button
    newName: ghcr.io/the-algovn/web-the-button
    newTag: main
    digest: sha256:5f943e747d565d73a20a6df686360f581e2bfc4878d2600254d62c7a2449ce0d
