apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: ghcr-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: algovn/shared/ghcr-pull
        property: dockerconfigjson
