---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAB2PKrICXP9mmK75MTu5tlRGdALL2Rmqz9EkPFcwlZwkQp+bFfjxrbW6O4qg6CUlaCHJFfaunTY7E4oYQXzwYzPxT1GUEZ6IAdxDL4nj5LY8iTBufaKubrNn4jKNqgn4U06jREtPBfmBI2GJrcAxiF0mbcV9FW0gBeJVyGBz96CqkdWaEhuG607yuvFxcEIPJNiu1+50cnqPKSi3F/aRtXC1iJiDUe77JoZlsWK6GKgNZgQDUUnXHvV/LJndM3eCh76PMI95hFeaB5RBZqOaL1EJofRI0lW3jrEwvDhEvgM5P4FW6am7zO1YHUCp+oOqxPWBTU9fJGTiukeCLc4WQrwS3MmnMM6+mlsSLRotBrj2tbRPXZnVab6xM2XeXn83oGsjvVAaddT8D6J3hJSc0eJXVcUJHSj0DvzcWFkG+iBQ1erMjDHiLyQBVqIexH2QkloVgRMMuxI8dRg/CXBF1Fj2ZOIpFQxOHPxbIDf3ZjjtRPikL+RZ0AbUREPvRsyvsk+xJYxlmA92FdsIa0oMw29ivz6dtKjCYO8ziZ/jiPmjr/469TE23j7HYm4CZfLH6M93WIxR1WSwVEMnG7m4tzWuvRnGrOn6C0c5HKYylRshl21rbuQ9PDD8m+42AC5jJm/ZWfU9j50aLiuTW5gsTlAVQPvCTYHqZSnmM6Jf/QXpBS9fsG3yjh7E1V2unil4eSxqFvgIZkGDDohpyEQt9RGVesC083h5cj3quAvYCZ6j6arlYBxlqlwkOBpmhNdS671E8G3X9V94poV7r5Dr5AcS1e9vJan7Mf64iaYbpSk4T7gmmwBxW2lSR1JMg=
    username: AgCwRFcIdTl3xTGv0+duDoTBpMcZhrtcvdMRjGzbVUyHkdjC28O7YbSKA/Jr22CbpXITNkJKnIRQSigSZo131RbmURMQ6JvkQqMlujHCjqAKyh4CCRmfBmdwikIiRMwT6VQXlclW5oIvTJMlEgT+x5cZ9nnaLizFtVtbEn+SPBdpUP2jCYMYC0AHj4xPcHNOqjJGNwE0/4sR+vJA+BYZFXSbtJXvOpviUwX2LzenUadOJuQUKo2O6riXqppLWKNJqdgL+tsFnO1olpozY6db9ut/ReQgPp4oi9m6J5TR5iPoUWK2jgqVpztOsDQthGl5tAodRGFpce2gASwhZwKc2nNqgK/V0QYDO/CpltT+LZmgqLdZ1uS52GBOKwzPcNMVBd1eNnCqe+iZ56G8aGNTzP2dXutDPDz8oYDy07yA66beuRV/bBNL60frCrkeZtnctnjv/aN95meAFV3d5ldDgFBomGEvHhjs9k3n4YxvTwKPb9B0Fjdu14J/dDTfbjCj//6kadshjYwdxerQx1pzMKRKHwy+AAB89JLhpZweEJiMQfKvrTPh0Df+Lz46yef1lEPDz+Wb9/rvKdbBX+mNW58vuTMSZviSmrlTVppNoE5eyCUyffH0yB6N92nt4zDPW49Ll2fbrKFEvqytBGfpouOx1WUEoTdXUm+rOGBJ9QuTsSsdXCgQm5AVD2GhP3aps6AOqai1G5m+NwQ=
  template:
    metadata:
      name: git-creds
      namespace: argocd
