apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-creds-external.yaml
  - ghcr-creds-external.yaml
  - showcase-updater.yaml
  - landing-updater.yaml
  - api-control-plane-updater.yaml
  - demo-service-updater.yaml
  - the-button-updater.yaml
  - the-button-web-updater.yaml
  - console-updater.yaml
  - radio-updater.yaml
  - radio-service-updater.yaml
