apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: the-button-web-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: the-button-web
      images:
        - alias: web-the-button
          imageName: ghcr.io/the-algovn/web-the-button:main
          commonUpdateSettings:
            updateStrategy: digest
            pullSecret: pullsecret:argocd/ghcr-creds
          manifestTargets:
            kustomize:
              name: ghcr.io/the-algovn/web-the-button
      writeBackConfig:
        method: git:secret:argocd/git-creds
        gitConfig:
          branch: main
          writeBackTarget: kustomization:.
