apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: the-race-service-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: the-race-service
      images:
        - alias: the-race-service
          imageName: ghcr.io/the-algovn/the-race-service:main
          commonUpdateSettings:
            updateStrategy: digest
            pullSecret: pullsecret:argocd/ghcr-creds
          manifestTargets:
            kustomize:
              name: ghcr.io/the-algovn/the-race-service
      writeBackConfig:
        method: git:secret:argocd/git-creds
        gitConfig:
          branch: main
          writeBackTarget: kustomization:.
