fullnameOverride: argocd-image-updater
config:
  registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      default: true
      credentials: pullsecret:argocd/ghcr-creds
resources:
  requests: { cpu: 25m, memory: 64Mi }
  limits: { memory: 128Mi }
