- name: restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: restart postgres exporter
  ansible.builtin.systemd:
    name: prometheus-postgres-exporter
    state: restarted

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
