apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: landing
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels: { app: landing }
  template:
    metadata:
      labels: { app: landing }
    spec:
      containers:
        - name: landing
          image: ghcr.io/the-algovn/web-landing:main
          ports: [{ containerPort: 80 }]
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: 25m, memory: 32Mi }
            limits: { memory: 128Mi }
      imagePullSecrets:
        - name: registry-creds
