apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  namespace: landing
spec:
  ingressClassName: kong
  rules:
    - host: algovn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing
                port: { number: 80 }
  tls:
    - hosts: [algovn.com]
