apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-landing
    newName: ghcr.io/the-algovn/web-landing
    newTag: main
    digest: sha256:4c9541ca57a437d43cedb59dcdd6820564a3d56269b0592242725b0d17644e9d
