apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-landing
    newName: ghcr.io/the-algovn/web-landing
    newTag: main
    digest: sha256:4b27d5f7e8f76933248e8a52a55516d48188e6b50ef02126b0d4a07251d60127
