apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-landing
    newName: ghcr.io/the-algovn/web-landing
    newTag: main
    digest: sha256:022090f5bedca8f7bf24f3e4b61d350fa1cc1e27ec6031752851d5a9cfde93ab
