---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-creds
  namespace: landing
spec:
  encryptedData:
    .dockerconfigjson: AgBfP1upy41+UKSia0CYsbT8QaxccSYGRYKkRg7wIJESMZ0eFk4FjAs2cN0epuFrtu1paZ0iZ8Y/MAKLorJ9Sj9AxCnYvLhE8IHYyDbzQfrrY1cG1BFRLgJhHXnXHhxWPO9J9i9LoD9unSloUCgcpT1Bbsa5NbmUa0NF/b/YF1+0PXJxAv6JZJ2PEex+Aq1Etz3394DXoONd4kGyTR4KXE+ZYktu+IiHNPcbZ89fwVGxWUZlm48opEXCJn+3JHZWJ6vUPyBWBIoKnzdY+lDAb9QjCZCEoBjviY1YU9scRot9s3+8yWjDagBlLON4iX/TOCyLTrx8q8GCqr57KpIwdgErm0NvXkMxOElrqNFXnbjHYsowUP5v22gOboz7dl4RHh5IOirZPdSafi0+ra29y+61gCIn/FMWf9uqoT7F/eVgirbuJZnXyduaF8ZNGfjObaWqFKa7uWdSw68Q4T0PEaQhOnJds8u3Y/MICNHekf5lz2WrY74p3epUxzR/iP7/Iega+uK2AtrbdzZMgeJ3ywMFPg3kIOlpI4tUuaeEma+I4Qtf9VI3uDdrPBgcrPvaj+ikXLcQolKmI9VOJo1uJCioILGN++wfVM1dDozPLlab4WHXWp5kiS+ZV8fZ/ldxPHhLi/E5XyLNnZqN8cjRAtyERnxpL7cMmueN7kjpm+XA8Vi+6QFK7ms3jBAsZT5LA1JU/qkJ1ucwcwOKOBbcqgGWqk25j/1m5AYSklgVXabQrvsF1zdDwC0U3P7FJHdB94z1GimeFQXlUWvhcHPJ8sdLYHfMeXN49cJ/7dhvAFbq5tsgiHvLRvKWEubQgoTA4E1eoQEajotSINBJR/YiWgM1oE4G1EYvj6+/SpkbOKqTsFDHbMnkdlSMh2GSJ+ZIt0/Kli/V55FA6vm0OVO8OUyttauqGdXBidRfWYHRcBJwxJTO
  template:
    metadata:
      name: registry-creds
      namespace: landing
    type: kubernetes.io/dockerconfigjson
