apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-console
    newName: ghcr.io/the-algovn/web-console
    newTag: main
    digest: sha256:da97872de319bb6ff1794f978b1e72b8ac12af4f0445ab1c692185aeb00a3360
