apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-console
    newName: ghcr.io/the-algovn/web-console
    newTag: main
    digest: sha256:b6ebf0f59bbbada034eeff3801de8a7734c04b2ac29a1763c19ef730be655575
