apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-console
    newName: ghcr.io/the-algovn/web-console
    newTag: main
    digest: sha256:08fda98fa1506fdf34cd965abf8bf8186ab4eff3c7895e0f4e90ad80765f2f3f
