all:
  children:
    server:
      hosts:
        algovn:
          ansible_host: 192.168.102.111
          cloudflared_tunnel: algovn-cp
          cloudflared_ingress:
            - { hostname: ssh-cp.algovn.com, service: "ssh://localhost:22" }
            - { hostname: k8s.algovn.com, service: "tcp://localhost:6443" }
    agents:
      hosts:
        algovn-w1:
          ansible_host: 192.168.102.112
          cloudflared_tunnel: algovn-w1
          cloudflared_ingress:
            - { hostname: ssh-w1.algovn.com, service: "ssh://localhost:22" }
  vars:
    ansible_user: ducle
    k3s_version: "v1.36.2+k3s1"
