apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - podscrape.yaml
  - db-zitadel.yaml
  - pg-role-zitadel-external.yaml
  - db-openfga.yaml
  - pg-role-openfga-external.yaml
  - db-the-button.yaml
  - pg-role-the-button-external.yaml
