apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - podscrape.yaml
  - db-zitadel.yaml
  - pg-role-zitadel-sealed.yaml
  - db-openfga.yaml
  - pg-role-openfga-sealed.yaml
