---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-role-testapp
  namespace: postgres
spec:
  encryptedData:
    password: AgAsFfrZKcbpgkntXU7isb7Uw1Peya84HENDrpc58BbXpGuWuShOBUldf9tXYc56FqgK+qzJ73+UJ3yPrOIDKDMs7LxXO5O5YYO6sqW6NPohNUcvbfUrkUjzJR3GJ3EyYdHFkCcy/mIA0W+tlYeI3VJCTJ9O/8Eai5Tj9RQxH68Jx35VYDMepUVJPvf8haiY8S+T0sulGi9nKCA189GHYoig5NCudAuapRBaQyiOzbvUe6y4P2BvGwGkG1vwZKUSksuUg2OODt0vPPqVc5frozbY2WVvDwaTRF/oUeyWflgQk1RlRszEBdcJ+PacE/hJUYV7gBGW3pyGbQs5dAsut4YqnyqjE2LxfXBKDVnK2qgqNcpUJ8NFYP5rz8BAC98h7liUSUr2svjql3yZTr3uKOZxbRTf80incksc96JM+2Ct8f6ts2TX3yT1c10vJFX9KzccKfT3tC9TfBiKal2ZPj6XxyHxx5ouHt/q+e/jb7J9TsZdiemV3AshcNnQ7/76Flq956BElcrIjA/zQN+SRHJro0XU4hHZyQUiXi2FoI8VcPSrl9mPWaGnRRqHXdJxeHcN1l2nKQyns86zQphYWXRpV7N5g8IEQFXEQouDwczwkTxwW1xuVVEN+BYkz6H3g6hhh5JaG1mcm/tK2kkteBgd9E/ZM/4ODu8ciqHLHMAS5k3B90F4CMuaptGa8P2ibLJ2R0VRTY0IXqWDWmIf8kOYFwThX2+K61FQXX2VsLaLWg==
    username: AgAfpuwP0URpJ8LyqM8MA0pGDyY7cf1GlJ6WSN1A6xSOSa3P4UFz/CMwbE+ZtKgehnBJgqWmWz4h2RBptNGAV/ptF7RrzkRkzaegwxlpsZ6x4JOJxfDeOwvM8R1DkZDa6tDEVxRvdocuZy7QwV7M8Cdk+lM95yVjXE0NwhE4ywE1xa3R8AhTGhXPQYiAnU9RA1gVdKp/n1DXsK5Ogl71kSFKk+3mtWKaQFm8yRP8qATGsjohzpYJYqLbedaAaeUiVxpKgRtL9fU1AV5OhFZ4D/SR793sPsLrhx/Rth2rkFUQbAadrS5nLtTUZd7OJ6TdC4UsPEDVTxKfftqtI0YontZxZXPBU2TpnApQIWxd8tsNCDZXYFdYQYHJ28l+vZgld9XCkzt2IO5F7GyKekM7nkOikLHRAci8GcSib7QhH7Pez/eIRHy5LsRxGZooHsOtnVmloT/t5LVdJDqdyOCTPa8xSWGz+G7Qzs+7GJA6TMDasiD2mQUZrRDkYWRMuffoLK0YO6YH+dvdLobKnCGEg6BAT0fGemkq85sxDfiSMn1x07xZLEYbxZA1ZswrsLxJVRJS7b1c0vP2MzJh5e95WaE2uoV1Q76trSkTY9Fvj0SLKHtyQoi6dHmygOxcxoKkM72RbDdJf0Fx19Y3YL0icveYrQO+8CAj19flNXcne4azwT8TS0i8OlV6EDsP/a+TBMYoFrHooSYI
  template:
    metadata:
      name: pg-role-testapp
      namespace: postgres
    type: kubernetes.io/basic-auth
