apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-role-the-button
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao
  target:
    name: pg-role-the-button
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: algovn/postgres/pg-role-the-button
        property: username
    - secretKey: password
      remoteRef:
        key: algovn/postgres/pg-role-the-button
        property: password
