---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-role-the-button
  namespace: postgres
spec:
  encryptedData:
    password: AgB7zzlCi1M11NW+TU9bz7XJXSYv8efIPMhV9TVvTdcM09iKW03d/H9DY3Pcj73clAkVLLjv835TBo5EiZZQuR/Bic6hhTs8r7cPSDrCfVZHUTRqBzcoMaePHGqLgER6q9rglUTNNERBND7ZbyUMm4g+URlbusXGz7gw4DPRZOve1GAPGuZUpm9ce8FAJ9DjB8Baj6zqu8jGfpnJhen6JwnH8zCJLbLDK/66JpcrnNBEeht3nj880SqcpDCh1KUihX9w3TWgfIdfXz+A8pWtMJRh9kqDTjPA4lBd0r/IImjpUZcEwQXBI0/GMPQdvGjJ7lhnhcru4WwCmyzR1oluxZIAM4p4ewgYaaBnTZb+f4Qi6XYOkE3NBITpHbXO/YYiduWpM2Yv3t/XAu3LELVQ/2Ral+mNfnI+sSTx4X+UANabiH0Udef1QWJAc0GlEEDdNwFzrHcRFIaMmarXG9/zSDVtSHgOyyzlAzSh+bXn8YetDFQLZt1xtpOQh5k4xbFF/vofXc52Vub7qCYcHoPZ20Ic1sWgLhO8OnxU+6yubMBtksoou4YTzx+8ud5aR6K4i49014brUtOHoFE1ZBF+/zcsFJKmNKJDDg8nmZ02Qv7cqpKw2qRRyEYsra+6pmeTsJ/AQ52G+SXx3lI+o844iBHARBL+KbS1Yyg0d2M25kAxOzulM6FCYEMtbSMs3rIf4okljORrrispbzQe3FiB3OA5/6oUtKpFoZl/5WBxMIvnmw==
    username: AgCnnoFWT6ihR/C1VuG0yVQwQDQehzeQkUXtMD6ok2nNrhwn7wian+ovYpN6Po4RsDLJvtyLi7Ij4YEByLBCRbl0g20WvTauMdeZmA53CWDppuLQLDAlGZRUCuuzGuxFhR1WIqO1IUo1abbqmu6wZ5i1BEkhRkBRMe9rB1K8xC7coAg/b992vsSt29N7NQPSlRmmX6HAnn2NAbfYa5VtKzgZJjMuEzw+Runu/RHe7o0eIT4/2kbV3HcQr9dk0dZMr+CQJAyTgMMvXO/yjxZPoYOyXUiWOoJ/dIq0daL2Wt/U/OuO5UbdrZSF4gYOfRjk3xoNGeg0isCj94xaRH5xmQKlEAbRC89ylnE37OKPi/Qv5TDSCTEP3OvXFHnRIcNNjhS19DPKoLthm5CdTZMlg0RLeRGRqFFgmrQtEIJUveEHu53f+A+zrwIwqJHx6m5VsJGcUG2S1MNRoy/S9ksoIxLPJfd9DYmNiRmCEK9ZxDyaw9DxIYWDYvTSL66UI34+VQGmzr96RUSo8caxS3D2PaTRP6yIPInfvs2LiVdoUbs5pwtTP4myTyrySyPsEyjxkDD4WngVtH16L1D4DsIoP/NIAXuSZE5eOnUgOqBSuGbg/42sG1Vy6YiDegRqqb+5wfMcPDuWXYIo9sHXPX6ogvEVhqsCV2greOocFXqqlwdU00G8gbpVEpZrR9miaXloyGm+75prJKrk6BDc
  template:
    metadata:
      name: pg-role-the-button
      namespace: postgres
    type: kubernetes.io/basic-auth
