---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-role-openfga
  namespace: postgres
spec:
  encryptedData:
    password: AgBYP+RF1pB3rpRRQfWjSl4srFbmae6OF4UuaSNCAhBe+5ZcuAlzAZq+8x/Nh+Wg56obPBMBSKpBdT0W0csciFoPu7KLd9+yGVzNzdisN4fwQf3mIF7x+cspC81RbLgyBoC+jKuZ8YNaDmzh54bdQKj/FC0SnXfTlUhBNmN+HeQfqbgEA7GNlCHafB3bwJxndaMkaqpSAlzgrZS9DpHUhGXYvTgXs5qMF/WczL/JLTdGq0GXcUdM9yoe9HaImlzPAJ2TkyTolmmt+M2G1Y3mqUhpZ65pZAyLsdOerUI2n0pIclGy/YXcx88vFTVmQMqN7OQs0QCrz6RWU5zY+DUi+KzNWb5gr88GFtGpfxOs2sob7znDfOlvwXYg2BmVFTXa5Y1wOw4F+LWbTes1CWyojHBHLGbvdg9LP7iWRhkOHAUIeN9x5/LJdwd+hjIh1D2vy3IToLViPje5cBXQGPfwmzfzxxKL+UNNVKY/L1i0nVi3IoqxHuibHaDo3VJyypQ/IzCnZu+gV3SW0rFdn1kLfmsM0wmDk2GZSwR8PswsXi1lFi1ny7YIXjdFCKhWPax+FF4ChKx62rXhNIkkSRzlLDPhdOPthGNZPvsSwOAuQ1zASNQ+c3STHTPyCG8IR0qu82aDzNcMK+p0fIe1Ij0vQhKuJ1t7MWg1j6yGpfGAbY4B0F/onX2efXRdaeRWAzy9pnFCdbhmA0E5rCkQ7UxLmA2Cr720PPre9+9UQOCDrD0RCA==
    username: AgCw7zYIUmUKHNa+XJTB29aW+RVnihCvT/2b82RFK8saZE7z5YFlwDepmQSXahWsUHwzmDmT+3MS/h3j4wO0VcWiduX4ALuBhkgb9p7YhjaO5maeU8PBYAploaALqq0khXc9dLOvLgx3KT/rAERXmUgtZvnTVdH06MDHnRUYYm9muINwkZaZRCjmzApjyBmbxaOdq/db7Qhpe/t5HMs2v9CxwZw6SW2q8WmCqt8OtGciFGb8CgqZdI47d5AOPDKEWVsBfn/S2efU/LK1ahn2hLCjvboAqovtKKKMPxrphFaTSU+m7v/ggqS29OdwXcDLnU2EdbQfAv5lec7WCq+LqbUxNXYbcr8N+0xfbwUPScXpza5705eBuzRuQtRPjIcpNArLGJaAnoJ/b7hbaVKrTPXx9ySyT9qxhGVGIdsvV0r4QJvQlrvyZwzxwTOQw59yHNLBr/UezBJ4+6N0XTTqx53SD5iuxHT9qeM/kQPuhxdZpO/Prnc/uEPRUf49lxEWtLDekhMIVDL4a5nBCaBPW5f/i+IaSlnf93Jfw1ac4OItCwWnb+rik4K1RkToNxDbG15IOdtHNY6y4qbuG+TofzHNB4uul69oo4u/KFxN9sVHLCb15ntvN2HNSs6LR4pDU0+2Le3aLdxvg8DhExheAYgZMzdvJQ6leHHw7CAJ8rbkGmQUNHxKFkLjvN+KNm8QBoWs1iNMoCo8
  template:
    metadata:
      name: pg-role-openfga
      namespace: postgres
    type: kubernetes.io/basic-auth
