---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-role-zitadel
  namespace: postgres
spec:
  encryptedData:
    password: AgAGmse0BS4Xf1MQtNaU3JmIfPkVR8qQjaqAp2suXKOakPFJTr8tM5Dx2rfRISJzZyOHrOTyHz1+AQhryy5wY/nPhlZkGe5LlGYOV6D3xEmoMg77VsvfX1nW425/u4Yuhun5Cct/p8AnmbnE0yTt2oVXtmr5/GDeysK3o/0lJ2IxKCLqRzyc7lulSHGbnFStR0DhmRWERdNxGjRw5kHdpcujz8zwo7JJfgE4R0N3RSLzBGNaKb3CxRmy5Pv2ZMv4rx9YnF0Gpea1+gL4/azfkKnq/A4qtMxlR7syfdioZp2SSR90xydaNslqrWDFjIK30pjRnl3XJgNUNzI/EehD/zft+4ULaI+Ika+sISr215zpooKOL8Ay16V6DESyfiavBDXfmVN93QE4szbFdtBLnozWmR++Sh/K6s7u3dOoe2g0adALHImYKhPBmrJYokqREm+dQfKcmN8vngjIzRO8MIcLUGRqOkijFGPVIySHekKV0zTL8X0BpQghL4tvtuFe2LcLBQFn6diKfsj4iKbZmkyIpdS921czfs5jPjyvx9GJ59gMDjkk22DkOvUnIw1aQegMsqPumztbqXzsHSMHOuE62RCtlp+ks7mwwyh50mX+sa4CpN6paMYIquHazPxptLygtT3dsHhicoSCAuxEKhtmuYNUWXIR2z9aiU93Dey93sQ2ba9vtVdF2v7LDygJfCU7QBYvrrsGkJDtpV/DISp/50A5ARLd5QqsXRnUz2WFPg==
    username: AgApoh2OrWMZzimqwQ7dl+N1fzLCXjU3rANNwncWRwEZHaHc9VnI1sBfsJrl85ih8KKPRMfZOxtvDfBe1BpTtpCxRc0mYtiwUjgoY49Wx9+1UnKuptTSrxhrqSKTOOjTDJDd7CnGzzvTXZepsaL2eTJXrwpPBY9oB+hChIOipF2c+3MQ5+SKdlzBjFZKgdbJ8JMsvKQUQiCDJ3cbs7u40UZfzDnSEN0luFLmVmgvndKxO4PqI22u5cWZEK0qz4aXuuJ9OAtCj7VqejjOuzITri5/P603t7rZ5Aw2aR3dQS/38cbSNA4KRJ89WZdXXnRsN7MKr2J2JBhVHwA5Blhzgv5rIoAGx7fktnCf3kyDwGtRIlPlRUavu2n5pwymMJOFGAFkXDejJRxUri6fDWA4PPlcFQ57EM3MGkeIMYZsgTTRiMgde6hw+GkVVuWFcLXwoFmC63XS8yG12WjhrA+uqB6ffIYZCLavmaymml6J1MBu/XgMb2ndkwbO/U7Hgz4Vtrfp1z5elx5MHSM9dMCqsPFrjr2rKK3nI2Acs5YduRS2IsS4mDncw3W9c3X3+3Uaqkt5zNoNodIikNn1TaGGSg1yEXZhPUg6TNRedcxoFzL8rqLNOMGRsB4s0I+NC53l9sQivIeihq9t22Pkytspv2ZyHAoHKT6L+kTt/IfwppKCmL0a87XYazMLaZF3EcqXVkQKEt/L4t98
  template:
    metadata:
      name: pg-role-zitadel
      namespace: postgres
    type: kubernetes.io/basic-auth
