apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.algovn.com
  oidc.config: |
    name: AlgoVN ID
    issuer: https://id.algovn.com
    clientID: "381964801196228977"
    enablePKCEAuthentication: true
    requestedScopes: ["openid", "profile", "email"]
