crds:
  enabled: true
resources:
  requests: { cpu: 50m, memory: 96Mi }
  limits: { memory: 192Mi }
webhook:
  resources:
    requests: { cpu: 25m, memory: 64Mi }
    limits: { memory: 128Mi }
cainjector:
  resources:
    requests: { cpu: 50m, memory: 96Mi }
    limits: { memory: 192Mi }
