apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-claw-nfs
  namespace: video-claw
spec:
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 1Ti } }
  volumeName: video-claw-nfs
