---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: amqp-creds
  namespace: api-control-plane
spec:
  encryptedData:
    url: AgB6p0bbenOeJocnAjUBP+3qnwprSaWQPCL/KA4rmyynBvxKpasD8P5Dh+vPZ0foTh00PBFXdFp1ZR3gft1CpvYV15FJD/LA8JLvZtlJvYNtkgxPo7MnKs/08tCGoostp0DTGFjLhZr8V5MNBknMk+9CAcJ8gWdsAK1r+Pd3ZOZ5/pgTdpKtLHDI8BLGWwTeg5zH711hN1MAa3ujZnU00OazUnOMqSd/LEWvPu5eNAO4exIhyqiTzgB0zT7sAldNJZdxevaqcNEfYVP/dlIxPSAfw6CltlubnCSulKj0j1EXu/HagOMM5F349OMnCKCjUlZIDvngXZIeynf6UnwMyY/eu3n2NyhkjRfQCR+mYEAzvKlxKWGR0lVDRv/O+JGOVj9ON5utTZwJaMFoiII9RqIBSQzOkj8rNxeucaYUNrpH/k3tq8lgVTg1AyeY5dIsacPPlGiTEm2grDwKbqPuH07Ubl31nK0+mZIhhKtOTTRUm1BD6po2GI7pBiPidZXCdH1Kew5gjLuJW1y02kqYzNmPuBSwVpQWtUDpbp6q73f/ZscDfsMp19LnLgeZwf7NfXzPfrUrC5ExUxDH9PbXeYWXanp8t3LwEh2h02obf7RgxPUnbaQ+LIfjaetQMc49ZZioAg84dxU0rPEY7ck002SBThym559q6l+VKur0wELuSZT18zxbvaWqHoAIZ4ekWQsTmpOLRHEmy/GoH4E+Yeey6r+FtUVOhRYOLMEcg1SnQMfcV7qehhI4AFBHtYmIyjfzQWFvARDTt/7vjtTYcWS+vFWVIq0SF0vSb+Tb0sNCX5Ytl6R6DXdo
  template:
    metadata:
      name: amqp-creds
      namespace: api-control-plane
