apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - amqp-creds-sealed.yaml
  - registry-creds-sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - vmservicescrape.yaml
  - rate-limit-plugin.yaml
configMapGenerator:
  - name: api-registrations
    namespace: api-control-plane
    files:
      - registrations/demo.yaml
generatorOptions:
  disableNameSuffixHash: true # stable name => ConfigMap updates hot-reload in place, no pod restart
images:
  - name: ghcr.io/the-algovn/api-control-plane
    newTag: main
    newName: ghcr.io/the-algovn/api-control-plane
    digest: sha256:3034ef4f9e7b10bf38000f70687b235bff4488f980d45e8c1f9662d862c409a2
