---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-creds
  namespace: api-control-plane
spec:
  encryptedData:
    .dockerconfigjson: AgAp1mn/NBGdKL4FRsRtmj/ND0dvUxZWoQhmPgaSdthJBY51s0WeQA49s3+kzGRK92qWr3+3OA2MetevKcWnodKxjkQ1/wl3VpRnhTXoTtFZVWLvF7KC3fa3mwUu4sZKSNYUdsVCrY4YuudWScD2rgocHTtCaYL8Qn4zfobG0rugfNCmJYvAyTWHLEomX+AWSwBFtSRbDdxZMG1HZt84w6Z7im7noBpOxLAVDDGVwdWpl+8+4YOGRzXC66l5FticvfkDjjEjAWVxTiWl3zA2lIMVZNY+TR7F7KQBCkAf/jP/s5D17O6EYk9U4qNsccu5DM+DvkeBm8iOS/DVqiQkpY9WSq8mrPFNQqIfIy5o+NdKm7rDLqyl8bVmXLoZgKA9bFoSuRvvzQ8SmlEjH8l7zu53DAp5hz/o+M/NC51Z5aAm/6YOqLZB6u7OZDNtuhFCw6J1B7ESy8D6mDrrmNHgVUGFBcF7ePsAdAThrIVNy57uSdsKxcga8BzXdbGU4oY88GV4q5+Q0HJokFFEVcotQ7jhorj0b6aCurz+ORL3DG6JloNcS/cqmvV8QCdFMlXU9+H4Op2/qGjsaJ0hi7T1p5/xHDuA7sMnRHW2hV/O/5cchZE0dDMsuYO/TOaNV8vPt1WyD+IXJ8DU7re7z/C2OLf+cvf8D8kE4uUoa0XtO1jZsuhMLOFfiR/9W4KEsLDIB4J8AkolKv/01JizCen8fVn4W6JHLdIuhRQJtRqFl/jW08RtLNUddXNoEMLFymq5ZzLmY+yahGq+wUZpBZTFQYABdp23932DfqfihmlIJBRvflE1T5izE3ZdOn1zdCi1nT0oOorZpPzuNnTt3iBfrHmRdIKndSm0jRjm9ZQ7e7h8nlW5EcTEC+T4oEeeM2rd8KSDtyljj/2NQym1gnvMTQODTYK1t4K0Qc/+Si3xiinVbZ11
  template:
    metadata:
      name: registry-creds
      namespace: api-control-plane
    type: kubernetes.io/dockerconfigjson
