apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-radio
    newName: ghcr.io/the-algovn/web-radio
    newTag: main
    digest: sha256:d2a60d2a92b1a7ea241405a98124f1ae3615f8ce03f8dab79e1da5bb805179ef
