apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-radio
    newName: ghcr.io/the-algovn/web-radio
    newTag: main
    digest: sha256:85d9df455c2a6ff8d6450cb1a76f796f285ab9d89061a9894e6bd5ec5324e629
