apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-radio
    newName: ghcr.io/the-algovn/web-radio
    newTag: main
    digest: sha256:6465ab9cdcb83ad19c3071f89dc519c7a30205ea0bdb6a2230ef9ed44d802c67
