apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-showcase
    newName: ghcr.io/the-algovn/web-showcase
    newTag: main
    digest: sha256:4fb4242387534b39b19dbaac70531eb4945222ce1868fa94443bbd02edc3d5de
