apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-showcase
    newName: ghcr.io/the-algovn/web-showcase
    newTag: main
    digest: sha256:79b2861267988710f08c43b91cac889e8fcc6ffad3168c9c1d085d6789f9fd57
