apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-creds-external.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/the-algovn/web-showcase
    newName: ghcr.io/the-algovn/web-showcase
    newTag: main
    digest: sha256:5bb8c59c3fea30ad8fe6f61b8e56d193470a4cca1febe534a064364f006f1da5
