---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-creds
  namespace: showcase
spec:
  encryptedData:
    .dockerconfigjson: AgCFzd3sseCLEWhua2seIhyleWtEclj1yRT0IeASqxMg4uJfRjnOjAvxE5OeeLWsJynWGw6PbM7thkeo+zLwNGy/M4b29YLaxeSDpuUm5qwp8oVmEYFwzMWqfuxlfayHMgamyx4bvNdQxvpVSEGbzZb9OtbP8QMPvvnkdSoiNe6jLFqC/n1N0oK1VFZNMmy3hhEOH3wrRFERWOWNl5U/uRA/IziObmHV0XFuBoBl5bnYTswf9unKa4JEhOFxnNPMDsD845uitKQ73jojC70g/85kXazMLJmDxK6mzdwZLMHqqWm2wybgc+zEREFXW7BnJEwJ4yRv2NjAokLPrw3HtAIzUd8XsXpXKSEXEjh0Bs2k86hQGNm4UDzFG7KavVx512j884ITCT97foGKm1ehMKqFmfyM5FLe9Oh1ZbuncnZfX5BvMm6bt3sh0lWbHyuqcRzjEOH6nqFUwjNtSmPyfisxs3Inr4TJanWPw6w/1qTJxw2hqxSGDcJqnJq3Pj7rYPYKIUugvta9tSkFUf4Tdv9YUwW2tXjAz1E2RShkPsFsEmEFIt8icGNASpnoOD9vn15uZ9IcNzcHoH3pTfFXQxlUps1W/4Fj+WMSXjfiX1UOfO0qDkUNDF1K4Afwimh/KTa2dvgOFF425fJlGvvD4PRfSO9xvaycpvmkM98b1h2hoZdKxeNdyYYkSWbp9PItatB+6ixb6vStegYututBgIpCjEMw+075ZVSWLdhDZ7gHXwr/ftf/1h5AyIu6OB97/PY7LNT7ziTX47yCHSJT3SuIadJZwHKWNy8bo+glImIXCLjv21wuJnY6QWj0qek+H2UZbssmdUua63FsLYQVcAS8dlpx/IJF7hcuwNpCqIpmi7eQQNZ5NA2TQRYRQ3DTYK0C3rsKlKRWek2a8XLXLfC2FA+jf0BDsoVPzFz6rSSSLZoj
  template:
    metadata:
      name: registry-creds
      namespace: showcase
    type: kubernetes.io/dockerconfigjson
